### ISSUE TITLE
Unable to train insightocr on VGG_Text data

### ISSUE THREAD

**Issue by madhav1ag** [deepinsight/insightocr#8]
Hi,
I am not able to train insightocr using train_crnn.py file.
I have downloaded the Synthetic Word Dataset(10GB) from VGG_Text.
Then i have made following changes-

- In config.py, 
        default.dataset = 'vgg'
        dataset.vgg.dataset_path = 'path of vgg dataset'

- In train_crnn.py,
        In line 70- image_set='annotation_train'
        In line 71- image_set='annotation_val'

annotation_train file contains data in following format-

> ./2425/1/115_Lube_45484.jpg 45484
image_name index
 
These index are mapped to label in lexicon.txt file. But in the entire script, we have not passed the path of lexicon.txt file. So how the model is going to train.

Kindly provide some solution to train it on VGG_text dataset. 

Also what is `config.image_path` in config.py?

**Comment by mdv3101** [comment]
Please reply.
